name: "Winterpeak"
description: "30% more arrivals"

overrides:
  arrival_streams:
    - id: "arr_ed_spoed"
      model:
        scale_factor_by_month:
          "12": 1.3
          "1":  1.3
          "2":  1.2
